export const textStyles = {
  bold: {
    fontFamily: "ProximaNova-Bold",
    fontWeight: "normal",
  },
  light: {
    fontFamily: "ProximaNova-Light",
    fontWeight: "normal",
  },
  regular: {
    fontFamily: "ProximaNova-Regular",
    fontWeight: "normal",
  },
  semibold: {
    fontFamily: "ProximaNova-Semibold",
    fontWeight: "normal",
  },
  heading1: {
    fontFamily: "ProximaNova-Semibold",
    fontWeight: "normal",
    fontSize: 32,
    lineHeight: 40,
    color: "#15141E",
  },
  heading2: {
    fontFamily: "ProximaNova-Semibold",
    fontWeight: "normal",
    fontSize: 24,
    lineHeight: 32,
    color: "#15141E",
  },
  heading4: {
    fontFamily: "ProximaNova-Semibold",
    fontWeight: "normal",
    fontSize: 16,
    lineHeight: 24,
    color: "#15141E",
  },
  bodyRegularBold: {
    fontFamily: "ProximaNova-Semibold",
    fontWeight: "normal",
    fontSize: 16,
    lineHeight: 24,
    color: "#15141E",
  },
  bodyRegular: {
    fontFamily: "ProximaNova-Regular",
    fontWeight: "normal",
    fontSize: 16,
    lineHeight: 24,
    color: "#15141E",
  },
  bodySmallBold: {
    fontFamily: "ProximaNova-Semibold",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: 18,
    color: "#15141E",
  },
  bodySmallRegular: {
    fontFamily: "ProximaNova-Regular",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: 18,
    color: "#15141E",
  },
  labelMedium: {
    fontFamily: "ProximaNova-Semibold",
    fontWeight: "normal",
    fontSize: 16,
    lineHeight: 24,
    color: "#15141E",
  },
  labelSmall: {
    fontFamily: "ProximaNova-Semibold",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: 18,
    color: "#15141E",
  },
} as const;
